[package]
name = "sov-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = { version = "0.10.3", features = ["bytes"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.6"
jupiter = { git = "https://github.com/Sovereign-Labs/Jupiter.git", branch = "upgrade" }
accounts = { git = "https://github.com/Sovereign-Labs/sovereign.git" }
election = { git = "https://github.com/Sovereign-Labs/sovereign.git" }
sovereign-sdk = { git = "https://github.com/Sovereign-Labs/sovereign.git" }
sov-state = { git = "https://github.com/Sovereign-Labs/sovereign.git", features = ["temp"] }
sov-modules-api = { git = "https://github.com/Sovereign-Labs/sovereign.git", features = ["mocks"] }
sov-modules-macros = { git = "https://github.com/Sovereign-Labs/sovereign.git" }
sovereign-db = { git = "https://github.com/Sovereign-Labs/sovereign.git", features = ["temp"] }

anyhow = "1.0.62"
jsonrpsee = { version = "0.16.2", features = ["http-client"] }

[patch.crates-io]
# Patch borsh until "bytes" support is added
borsh = { git = "https://github.com/preston-evans98/borsh-rs.git", branch = "release-2" }

[patch.'https://github.com/Sovereign-Labs/sovereign.git']
sovereign-sdk = { path = "../sovereign/sdk" }
sovereign-db = { path = "../sovereign/db/sovereign-db" }

[patch.'https://github.com/Sovereign-Labs/Jupiter.git']
jupiter = { path = "../jupiter" }
