start_height = 293685
namespace_id = "0x736f762d74657374"
[da]
celestia_rpc_auth_token = "SECRET_RPC_TOKEN"
celestia_rpc_address = "http://localhost:11111/"
# 100 MB
max_celestia_response_body_size = 104_857_600
[runner.storage]
path = "demo_data"